// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

#ifndef PROTOBUF_client_2eproto__INCLUDED
#define PROTOBUF_client_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "types.pb.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

namespace Xenophobia {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_client_2eproto();
void protobuf_AssignDesc_client_2eproto();
void protobuf_ShutdownFile_client_2eproto();

class Disconnect;
class DoAction;
class RegisterName;
class RegisterRole;

// ===================================================================

class RegisterName : public ::google::protobuf::Message {
 public:
  RegisterName();
  virtual ~RegisterName();

  RegisterName(const RegisterName& from);

  inline RegisterName& operator=(const RegisterName& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RegisterName& default_instance();

  void Swap(RegisterName* other);

  // implements Message ----------------------------------------------

  inline RegisterName* New() const { return New(NULL); }

  RegisterName* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RegisterName& from);
  void MergeFrom(const RegisterName& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RegisterName* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:Xenophobia.RegisterName)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_client_2eproto();
  friend void protobuf_AssignDesc_client_2eproto();
  friend void protobuf_ShutdownFile_client_2eproto();

  void InitAsDefaultInstance();
  static RegisterName* default_instance_;
};
// -------------------------------------------------------------------

class RegisterRole : public ::google::protobuf::Message {
 public:
  RegisterRole();
  virtual ~RegisterRole();

  RegisterRole(const RegisterRole& from);

  inline RegisterRole& operator=(const RegisterRole& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RegisterRole& default_instance();

  void Swap(RegisterRole* other);

  // implements Message ----------------------------------------------

  inline RegisterRole* New() const { return New(NULL); }

  RegisterRole* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RegisterRole& from);
  void MergeFrom(const RegisterRole& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RegisterRole* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .types.Role role = 1;
  void clear_role();
  static const int kRoleFieldNumber = 1;
  ::types::Role role() const;
  void set_role(::types::Role value);

  // @@protoc_insertion_point(class_scope:Xenophobia.RegisterRole)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  int role_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_client_2eproto();
  friend void protobuf_AssignDesc_client_2eproto();
  friend void protobuf_ShutdownFile_client_2eproto();

  void InitAsDefaultInstance();
  static RegisterRole* default_instance_;
};
// -------------------------------------------------------------------

class Disconnect : public ::google::protobuf::Message {
 public:
  Disconnect();
  virtual ~Disconnect();

  Disconnect(const Disconnect& from);

  inline Disconnect& operator=(const Disconnect& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Disconnect& default_instance();

  void Swap(Disconnect* other);

  // implements Message ----------------------------------------------

  inline Disconnect* New() const { return New(NULL); }

  Disconnect* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Disconnect& from);
  void MergeFrom(const Disconnect& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Disconnect* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Xenophobia.Disconnect)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_client_2eproto();
  friend void protobuf_AssignDesc_client_2eproto();
  friend void protobuf_ShutdownFile_client_2eproto();

  void InitAsDefaultInstance();
  static Disconnect* default_instance_;
};
// -------------------------------------------------------------------

class DoAction : public ::google::protobuf::Message {
 public:
  DoAction();
  virtual ~DoAction();

  DoAction(const DoAction& from);

  inline DoAction& operator=(const DoAction& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DoAction& default_instance();

  void Swap(DoAction* other);

  // implements Message ----------------------------------------------

  inline DoAction* New() const { return New(NULL); }

  DoAction* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DoAction& from);
  void MergeFrom(const DoAction& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DoAction* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .types.Action action = 1;
  void clear_action();
  static const int kActionFieldNumber = 1;
  ::types::Action action() const;
  void set_action(::types::Action value);

  // optional .types.Item item = 2;
  void clear_item();
  static const int kItemFieldNumber = 2;
  ::types::Item item() const;
  void set_item(::types::Item value);

  // repeated .types.ITarget targets = 3;
  int targets_size() const;
  void clear_targets();
  static const int kTargetsFieldNumber = 3;
  const ::types::ITarget& targets(int index) const;
  ::types::ITarget* mutable_targets(int index);
  ::types::ITarget* add_targets();
  ::google::protobuf::RepeatedPtrField< ::types::ITarget >*
      mutable_targets();
  const ::google::protobuf::RepeatedPtrField< ::types::ITarget >&
      targets() const;

  // @@protoc_insertion_point(class_scope:Xenophobia.DoAction)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  int action_;
  int item_;
  ::google::protobuf::RepeatedPtrField< ::types::ITarget > targets_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_client_2eproto();
  friend void protobuf_AssignDesc_client_2eproto();
  friend void protobuf_ShutdownFile_client_2eproto();

  void InitAsDefaultInstance();
  static DoAction* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// RegisterName

// optional string name = 1;
inline void RegisterName::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RegisterName::name() const {
  // @@protoc_insertion_point(field_get:Xenophobia.RegisterName.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RegisterName::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Xenophobia.RegisterName.name)
}
inline void RegisterName::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Xenophobia.RegisterName.name)
}
inline void RegisterName::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Xenophobia.RegisterName.name)
}
inline ::std::string* RegisterName::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:Xenophobia.RegisterName.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RegisterName::release_name() {
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RegisterName::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:Xenophobia.RegisterName.name)
}

// -------------------------------------------------------------------

// RegisterRole

// optional .types.Role role = 1;
inline void RegisterRole::clear_role() {
  role_ = 0;
}
inline ::types::Role RegisterRole::role() const {
  // @@protoc_insertion_point(field_get:Xenophobia.RegisterRole.role)
  return static_cast< ::types::Role >(role_);
}
inline void RegisterRole::set_role(::types::Role value) {
  
  role_ = value;
  // @@protoc_insertion_point(field_set:Xenophobia.RegisterRole.role)
}

// -------------------------------------------------------------------

// Disconnect

// -------------------------------------------------------------------

// DoAction

// optional .types.Action action = 1;
inline void DoAction::clear_action() {
  action_ = 0;
}
inline ::types::Action DoAction::action() const {
  // @@protoc_insertion_point(field_get:Xenophobia.DoAction.action)
  return static_cast< ::types::Action >(action_);
}
inline void DoAction::set_action(::types::Action value) {
  
  action_ = value;
  // @@protoc_insertion_point(field_set:Xenophobia.DoAction.action)
}

// optional .types.Item item = 2;
inline void DoAction::clear_item() {
  item_ = 0;
}
inline ::types::Item DoAction::item() const {
  // @@protoc_insertion_point(field_get:Xenophobia.DoAction.item)
  return static_cast< ::types::Item >(item_);
}
inline void DoAction::set_item(::types::Item value) {
  
  item_ = value;
  // @@protoc_insertion_point(field_set:Xenophobia.DoAction.item)
}

// repeated .types.ITarget targets = 3;
inline int DoAction::targets_size() const {
  return targets_.size();
}
inline void DoAction::clear_targets() {
  targets_.Clear();
}
inline const ::types::ITarget& DoAction::targets(int index) const {
  // @@protoc_insertion_point(field_get:Xenophobia.DoAction.targets)
  return targets_.Get(index);
}
inline ::types::ITarget* DoAction::mutable_targets(int index) {
  // @@protoc_insertion_point(field_mutable:Xenophobia.DoAction.targets)
  return targets_.Mutable(index);
}
inline ::types::ITarget* DoAction::add_targets() {
  // @@protoc_insertion_point(field_add:Xenophobia.DoAction.targets)
  return targets_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::types::ITarget >*
DoAction::mutable_targets() {
  // @@protoc_insertion_point(field_mutable_list:Xenophobia.DoAction.targets)
  return &targets_;
}
inline const ::google::protobuf::RepeatedPtrField< ::types::ITarget >&
DoAction::targets() const {
  // @@protoc_insertion_point(field_list:Xenophobia.DoAction.targets)
  return targets_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Xenophobia

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_client_2eproto__INCLUDED
